version: '3'
services:

  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"

  bot:
    build:
      context: "./bot"
      dockerfile: Dockerfile