version: '3'
services:

  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8001:8001"